In [1]:
import numpy as np

In [2]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
array_mod = array.reshape(3,3)
array_mod

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
array_mod2 = array.reshape(-1, 3)
array_mod2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
array_volteado = array_mod.transpose()
array_volteado

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [10]:
array_chato = array_mod.flatten()#crea una copia achatada de la matriz
array_chato

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
array_ravel = array_mod.ravel()# crea una vista achatada de la matriz
array_ravel

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
array_original = np.array(range(1,13))
array_original

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
array_reshape = array_original.reshape(3,4)
array_reshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])