# Funciones Universales de NumPy (ufuncs)

A continuación quiero dejarte un listado de las **Funciones Universales** de NumPy más comunes, **agrupadas por categorías**.

Este listado no es exhaustivo ya que existe una gran cantidad, y creo que no sería practico incluir aquí algunas funciones que son tan específicas que harían que esta tabla deje de ser práctica para ti.

En caso de que quieras conocer la lista completa, puedes hacerlo visitando [este enlace](https://numpy.org/doc/stable/reference/ufuncs.html) hacia la documentación oficial de NumPy (sólo disponible en inglés).

| Categoría                | Función       | Descripción Breve                                               |
|--------------------------|---------------|-----------------------------------------------------------------|
| **Aritméticas**          | `add`         | Suma elemento a elemento de dos arrays.                         |
|                          | `subtract`    | Resta elemento a elemento de dos arrays.                        |
|                          | `multiply`    | Multiplica elemento a elemento de dos arrays.                   |
|                          | `divide`      | Divide elemento a elemento de dos arrays.                       |
|                          | `negative`    | Cambia el signo a los elementos de un array.                    |
|                          | `power`       | Eleva los elementos de un array a las potencias de otro array.  |
|                          | `mod`         | Calcula el módulo elemento a elemento entre dos arrays.         |
| **Trigonométricas**      | `sin`         | Seno de los elementos del array.                                |
|                          | `cos`         | Coseno de los elementos del array.                              |
|                          | `tan`         | Tangente de los elementos del array.                            |
|                          | `arcsin`      | Arcoseno de los elementos del array.                            |
|                          | `arccos`      | Arcocoseno de los elementos del array.                          |
|                          | `arctan`      | Arcotangente de los elementos del array.                        |
| **Hiperbólicas**         | `sinh`        | Seno hiperbólico de los elementos del array.                    |
|                          | `cosh`        | Coseno hiperbólico de los elementos del array.                  |
|                          | `tanh`        | Tangente hiperbólica de los elementos del array.                |
|                          | `arcsinh`     | Arcoseno hiperbólico de los elementos del array.                |
|                          | `arccosh`     | Arcocoseno hiperbólico de los elementos del array.              |
|                          | `arctanh`     | Arcotangente hiperbólica de los elementos del array.            |
| **Exponencial y Logaritmo** | `exp`      | Exponencial de los elementos del array.                         |
|                          | `log`         | Logaritmo natural de los elementos del array.                   |
|                          | `log2`        | Logaritmo base 2 de los elementos del array.                    |
|                          | `log10`       | Logaritmo base 10 de los elementos del array.                   |
|                          | `expm1`       | `exp(x) - 1` para todos los elementos del array.                |
|                          | `log1p`       | `log(1 + x)` para todos los elementos del array.                |
| **Estadísticas**         | `sum`         | Suma de elementos en el array.                                  |
|                          | `prod`        | Producto de elementos en el array.                              |
|                          | `mean`        | Media de elementos en el array.                                 |
|                          | `std`         | Desviación estándar de los elementos del array.                 |
|                          | `var`         | Varianza de los elementos en el array.                          |
|                          | `min`         | Mínimo de los elementos del array.                              |
|                          | `max`         | Máximo de los elementos del array.                              |
| **Comparación**          | `greater`     | Comparación elemento a elemento (mayor que) entre dos arrays.   |
|                          | `less`        | Comparación elemento a elemento (menor que) entre dos arrays.   |
|                          | `equal`       | Comparación elemento a elemento (igual) entre dos arrays.       |
|                          | `not_equal`   | Comparación elemento a elemento (no igual) entre dos arrays.    |
|                          | `greater_equal` | Comparación elemento a elemento (mayor o igual) entre dos arrays. |
|                          | `less_equal`  | Comparación elemento a elemento (menor o igual) entre dos arrays. |


In [1]:
import numpy as np

In [2]:
A = np.array(range(1, 11,2))
A

array([1, 3, 5, 7, 9])

In [7]:
B = (np.array(range(1,len(A)+1)) * 10).reshape(5,1)
B

array([[10],
       [20],
       [30],
       [40],
       [50]])

In [8]:
resultado = np.add(A,B)
resultado

array([[11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59]])

In [9]:
C = np.array(range(1,11))
C

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
D = (np.array(range(1, len(C)+1))) * 10
D

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [11]:
resultado2 = np.multiply(C,D)
resultado2

array([  10,   40,   90,  160,  250,  360,  490,  640,  810, 1000])