In [1]:
import numpy as np

In [2]:
array1d = np.array([1, 2, 3, 4, 5])

In [3]:
array2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

In [4]:
array2d[1][1]

np.int64(5)

In [5]:
array2d[1,1]

np.int64(5)

In [6]:
array2d[1, 0:2]

array([4, 5])

In [7]:
array2d[1, 1:]

array([5, 6])

In [8]:
array2d[:, 1]

array([2, 5, 8])

In [10]:
numeros = np.array(range(1,11))
numeros

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
matriz = np.array(range(1,10)).reshape(3,3)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
segunda_fila = matriz[1, :]
segunda_fila

array([4, 5, 6])