In [1]:
import numpy as np
import pandas as pd

In [2]:
array_enteros = np.array(range(1, 11))
array_enteros

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
forma_array = array_enteros.shape
forma_array

(10,)

In [4]:
array_2d = np.array([[1, 2, 3],[4, 5, 6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
array_2d.shape

(2, 3)

In [7]:
array1 = np.array(range(1,6))
array1

array([1, 2, 3, 4, 5])

In [8]:
array2 = np.array(range(6,11))
array2

array([ 6,  7,  8,  9, 10])

In [10]:
array_concatenado = np.concatenate([array1, array2])
array_concatenado

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
array_original = np.array(range(1,7))
array_original

array([1, 2, 3, 4, 5, 6])

In [14]:
array_reshaped = array_original.reshape(2,3)
array_reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
A = np.array(range(1, 5)).reshape(2,2)
A

array([[1, 2],
       [3, 4]])

In [17]:
B = np.array(range(5, 9)).reshape(2,2)
B

array([[5, 6],
       [7, 8]])

In [18]:
suma_AB = A + B
suma_AB

array([[ 6,  8],
       [10, 12]])

In [19]:
productoAB = A * B
productoAB

array([[ 5, 12],
       [21, 32]])