In [1]:
import numpy as np

In [2]:
array = np.array([1,2, np.nan, 4, 5])
array

array([ 1.,  2., nan,  4.,  5.])

In [3]:
np.isnan(array)

array([False, False,  True, False, False])

In [4]:
np.mean(array)

np.float64(nan)

In [5]:
np.nanmean(array)

np.float64(3.0)

In [6]:
sustituir_nans = np.where(np.isnan(array), 0, array)
sustituir_nans

array([1., 2., 0., 4., 5.])