![](Bellman.png)

In [1]:
import numpy as np
import random


In [2]:
dimensiones =(5,5)
estado_inicial = (0,0)
estado_objetivo = (4,4)
obstaculos = [(1,1),(1,3),(2,3),(3,0)]
acciones = [(-1,0),(1,0),(0,-1),(0,1)]

In [3]:
num_estados = dimensiones[0] * dimensiones[1]
num_estados

25

In [4]:
num_acciones = len(acciones)
num_acciones

4

In [5]:
Q = np.zeros((num_estados, num_acciones))
Q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
#! determina la posicion del estado dado de la matriz
def estado_a_indice(estado):
    return estado[0] * dimensiones[1] + estado[1]

In [7]:
ejemplo = estado_a_indice((1,2))
ejemplo

7

In [8]:
alpha = 0.1 #determina cuanto se actualiza el ajente Q en cada iteracion
gamma = 0.99 #factor de descuento, determina la importancia de las recompensas futuras
epsilon = 0.2 #tasa de exploracion, determina la probabilidad de que el agente explore nuevas acciones en lugar de tomar la mejor que ya conoce
episodios = 100 #cantidad de veces q se repite el proceso de aprendizaje


In [15]:
def elegir_accion(estado):
    if random.uniform(0,1) < epsilon:
        return random.choice(range(num_acciones))
    else:
        return np.argmax(Q[estado_a_indice(estado)])

In [10]:
def aplicar_accion(estado, accion_idx):
    accion = acciones[accion_idx]
    nuevo_estado = tuple(np.add(estado, accion) % dimensiones)

    if nuevo_estado == obstaculos or nuevo_estado == estado:
        return estado, -100, False
    
    if nuevo_estado == estado_objetivo:
        return nuevo_estado, 100, True

    return nuevo_estado, -1, False

In [17]:
for episodio in range(episodios):
    estado = estado_inicial
    terminado = False

    while not terminado:
        idx_estado = estado_a_indice(estado)
        accion_idx = elegir_accion(estado)
        nuevo_estado, recompensa, terminado = aplicar_accion(estado, accion_idx)
        idx_nuevo_estado = estado_a_indice(nuevo_estado)

        Q[idx_estado, accion_idx] = Q[idx_estado, accion_idx] + alpha + (recompensa + gamma * np.max(Q[idx_nuevo_estado]) - Q[idx_estado, accion_idx])
        estado = nuevo_estado   

In [18]:
politica = np.zeros(dimensiones, dtype=int)
politica

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [20]:
for i in range(dimensiones[0]):
    for j in range(dimensiones[1]):
        estado = (i, j)
        idx_estado = estado_a_indice(estado)
        mejor_accion = np.argmax(Q[idx_estado])
        politica[i][j] = mejor_accion

print("Politica Aprendida: (0: arriba, 1: abajo, 2: izquierda, 3: derecha)")
politica

Politica Aprendida: (0: arriba, 1: abajo, 2: izquierda, 3: derecha)


array([[0, 2, 2, 1, 0],
       [2, 3, 2, 1, 0],
       [1, 1, 2, 1, 0],
       [1, 1, 2, 0, 1],
       [2, 2, 3, 3, 0]])