# Indexación y Segmentación de Arrays

En esta lección vamos a aprender cómo:
* **acceder a elementos específicos** de un array de NumPy a través de la **indexación**,
* cortar (o hacer **slicing**) a nuestros arrays para obtener subconjuntos
* usar **índices booleanos** para filtrar datos en los arrays.

Mucho por aprender así que comencemos.

### Indexar Arrays

En NumPy, puedes acceder a elementos específicos de un array de la misma manera que en las listas de Python, utilizando **índices**.

PAra estos ejemplos voy a crear dos arrays: uno unidimensional y otro bidimensional.

In [1]:
import numpy as np

In [2]:
array1d = np.array([1, 2, 3, 4, 5])

In [3]:
array2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

¿Queremos acceder al **primer elemento** de un **array unidimensional**?

In [4]:
array1d[0]

1

¿al último?

In [5]:
array1d[-1]

5

Fácil, esto es lo mismo que hacemos con las listas. Pero veamos qué pasa si hago lo mismo con mi array de **dos dimensiones**:

In [6]:
array2d[0]

array([1, 2, 3])

Aquí lo que he obtenido es el primer elemento del array bidimensional, que es **la fila que se encuentra en el índice `0`**.

Entonces si se da el caso de que yo quiero agarrar solamente el **numero 6** de este array (y no toda la fila en que se encuentra el 6), primero tengo que indexar la posición de la fila, y luego la posición del elemento 6.

In [7]:
array2d[1][2]

6

O también puedo escribirlo así… y es lo mismo.

In [8]:
array2d[1, 2]

6

### Seleccionar Subconjuntos (Slicing)

Otra estrategia que ya conocemos en Python, y que también podemos aplicar con los arrays de NumPy, es el **slicing**, para seleccionar subconjuntos de datos.

Para un array de **una dimensión**, lo aplicamos exactamente igual que con las listas:

In [9]:
array1d[1:4]

array([2, 3, 4])

Para arrays **bidimensionales**, puedes hacer slicing tanto en filas como en columnas.

Supongamos que quiero obtener la **segunda fila** completa:

In [10]:
array2d[1, :]

array([4, 5, 6])

Pero si quiero obtener los **dos últimos números** de esa fila:

In [11]:
array2d[1, 1:3]

array([5, 6])

También podemos usar el slicing para obtener **una columna completa**, por ejemplo la **columna del medio**:

In [12]:
array2d[:, 1]

array([2, 5, 8])

Y un caso particular sería que queramos obtener los **dos primeros números** de las **primeras dos filas** y las **primeras dos columnas**, por ejemplo:

In [13]:
array2d[:2, :2]

array([[1, 2],
       [4, 5]])

### Indexación Booleana

Y por último, quiero presentarte la indexación booleana, que nos permite seleccionar elementos de un array **que cumplan con una condición específica**.

Por ejemplo, quiero identificar qué números de mi array unidimensional son **mayores a 3**:

In [14]:
array1d > 3

array([False, False, False,  True,  True])

O talvez en mi array de dos dimensiones quiero ver **qué números son pares**:

In [15]:
array2d % 2 == 0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

La **indexación** y el **slicing** son herramientas poderosas en NumPy, ya que te permiten acceder y manipular datos de manera eficiente. 

La **indexación booleana**, en particular, aunque por ahora parezca sólo un juego de lógica divertido, es extremadamente útil para el análisis de datos, ya que permite filtrar datos según condiciones específicas, y vas a ir conociendo su utilidad práctica con el tiempo. 