# Manipulación de Arrays

Quiero compartir contigo algunos métodos y estrategias que nos permiten manipular arrays en NumPy.

Algo que también podemos hacer es **concatenar** a nuestros arrays, del mismo modo en que hemos concatenado DataFrames con Pandas.

In [1]:
import numpy as np

In [2]:
x = [1,2,3]
y = [1,2,3]
z = [1,2,3]

In [3]:
np.concatenate([x, y, z])

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

Como puedes ver, el argumento que hemos pasado a `concatenate()` es una lista de listas a concatenar, y esto a devuelto un **array** (porque lo hicimos con NumPy) **de una dimensión**.

Pero el método `concatenate()` de NumPy tiene un segundo argumento, que es el **"Eje"**, o **"Axis"**, que nos permite especificar a lo largo de qué eje será concatenado el resultado.

Voy a crear **2 arrays de dos dimensiones**, y lo voy a concatenar sobre el eje 1 `(axis=1)`:

In [4]:
a = [[1, 2],
    [3, 4]]
b = [[5, 6],
    [7, 8]]
np.concatenate([a, b], axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Y si concateno esos mismos arrays pero sobre el eje `0`:

In [5]:
np.concatenate([a, b], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Hay algunas estrategias extra para manipular arrays, como por ejemplo **cambiar su forma**.

Para hacer eso, primero voy a tomar el último array que hemos creado y lo voy a alamacenar en la variable `array_concatenado`:

In [6]:
array_concatenado = np.concatenate([a, b], axis=0)
array_concatenado

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Si quiero conocer la **forma** de este array…

In [7]:
array_concatenado.shape

(4, 2)

… veo que es de **4 por 2**, porque tiene **cuatro filas** y **dos columnas**.

Pero voy a **cambiar su forma**, pidiéndole que se reorganice para ser un array de **2 filas** por **4 columnas**, usando el método `reshape()`:

In [8]:
array_reformado = array_concatenado.reshape(2, 4)
array_reformado

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

También puedo hacer cosas como **sumar arrays**:

In [9]:
array_sumado = array_reformado + array_reformado
array_sumado

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

O multiplicarlos:

In [10]:
array_multi = array_reformado * array_reformado
array_multi

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

Básicamente puedes usar todos los operadores matemáticos que conocemos para hacer cálculos con arrays (ya sean uni o bidimensionales).

Un detalle específico en NumPy que me gustaría mostrarte es cómo hacemos en este caso el cálculo de la **raíz cuadrada**, ya que es con un método especial de NumPy que se llama `sqrt()`, que significa **square root** (o *raíz cuadrada*), y que se aplica así:

In [11]:
raices = np.sqrt(array_multi)
raices

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

Esto es lo básico sobre arrays, hay mucho más para aprender (sobre arrays en particular y NumPy en general), así que es hora de avanzar.