# Operaciones Avanzadas y Funciones Universales con Arrays

En esta lección vamos a aprender varios recursos que nos van a permitir realizar operaciones más avanzadas con arrays. Esto va a ser divertido.

Primero te presento al **broadcasting**, que es una estrategia que nos permite extender operaciones de un modo curioso pero muy eficiente.

Observa estos dos arrays que he creado. Uno es unidimensional, y el otro es bidimensional.

In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 2, 3])
array1

array([1, 2, 3])

In [3]:
array2 = np.array([[0], [10], [20], [30]])
array2

array([[ 0],
       [10],
       [20],
       [30]])

A pesar de que el primero tiene una forma **horizontal** y el segundo **vertical**, voy a intentar sumarlos. Por favor, analiza el resultado para comprender de qué manera funciona el broadcasting.

In [4]:
broadcast_suma = array2 + array1
broadcast_suma

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

Y a esto tambien lo podemos hacer con otras operaciones, como por ejemplo, la multiplicación.

In [5]:
broadcast_multi = array2 * array1
broadcast_multi

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

### Funciones Universales (ufuncs)

Lo segundo que quiero que veamos en esta lección, son las funciones universales en Numpy, también conocidas como ufuncs. Las ufuncs son funciones que operan en arrays de NumPy, pero aplicándose **elemento por elemento**, de manera **vectorizada**, lo que las hace muy eficientes. Veamos algunos ejemplos.

Primero tenemos las **funciones Aritméticas** básicas.

El método `add()` sirve para realizar sumas vectorizadas.

In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [7]:
resultado = np.add(a, b)
resultado

array([5, 7, 9])

Te dejo aquí los nombres de las demás funciones aritméticas básicas, para que pruebes por ti mismo.

In [8]:
# .substract(), .multiply(), .divide()

Ahora veamos algunas **funciones Matemáticas**.

Para conocer el **exponencial** de cada número de un array, puedo usar `exp()`.

In [9]:
resultado2 = np.exp(a)
resultado2

array([ 2.71828183,  7.3890561 , 20.08553692])

Tenemos `log()` para conocer el **logaritmo natural** de cada número:

In [10]:
resultado3 = np.log(a)
resultado3

array([0.        , 0.69314718, 1.09861229])

Como nota adicional, tambien puedes calcular el logaritmo natural para otras bases, como base de 2, o de 10, de esta manera:

In [11]:
resultado4 = np.log10(a)
resultado4

array([0.        , 0.30103   , 0.47712125])

Y finalmente, dentro de las funciones matemáticas, te quiero mostrar a `sqrt()`, que ya la vimos antes, y que sirve para conocer la **raíz cuadrada** de cada elemento de un array:

In [12]:
resultado5 = np.sqrt(a)
resultado5

array([1.        , 1.41421356, 1.73205081])

Hay muchas más funciones universales, como las trigonométricas, las estadísticas, las lógicas, hiperbólicas, y otras más.

Para no agobiarte con tanta información, te dejo [este otro cuaderno](Funciones%20Universales%20de%20Numpy%20(ufuncs).ipynb) que contiene una lista ampliada con las funciones universales más utilizadas, para que la tengas a mano o las practiques si quieres.

Como siempre insisto en que lo importante no es saberse de memoria todas las cosas que existen en Python, porque es imposible, sino sólo saber que existen para luego saber dónde y cómo buscarlas en caso de que las necesites.